configuration:
  - Debug
  - Release

install:
  - git submodule update --init --recursive

before_build:
  - nuget restore

build:
  verbosity: minimal
  project: libsass-net.sln

on_success:
  - 7z a libsass-net.zip .
  - ps: Push-AppveyorArtifact libsass-net.zip
